services:
  prometheus:
    user: "root"
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ${PROMETHEUS_DATA_PATH}:/prometheus
      - ${PROMETHEUS_YML_PATH}:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT}:9090
    env_file:
      - ../.env
    networks:
      - prometheus-network
  grafana:
    user: "root"
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - TZ=Asia/Seoul
      - GF_SERVER_ROOT_URL=${SERVER_URL}${GRAFANA_SERVER_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ${GRAFANA_DATA_PATH}:/var/lib/grafana
      - ${GRAFANA_PROVISIONING}:/etc/grafana/provisioning
    ports:
      - ${GRAFANA_PORT}:3000
    depends_on:
      - prometheus
    networks:
      - prometheus-network
networks:
  prometheus-network:
    driver: bridge
