services:
  backend-blue:
    container_name: backend-blue
    build:
      context: ../BackEnd
      dockerfile: Dockerfile
    image: backend-blue:0.0.1
    ports:
      - 127.0.0.1:${BLUE_PORT}:8080
    networks:
      - econimal-network

  backend-green:
    container_name: backend-green
    build:
      context: ../BackEnd
      dockerfile: Dockerfile
    image: backend-green:0.0.1
    ports:
      - 127.0.0.1:${GREEN_PORT}:8080
    networks:
      - econimal-network

  frontend:
    container_name: frontend
    build:
      context: ../FrontEnd
      dockerfile: Dockerfile
    image: frontend:0.0.1
    ports:
      - 127.0.0.1:${APP_PORT}:80
    networks:
      - econimal-network

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
    networks:
      - econimal-network
  
  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Seoul
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONF_PATH}:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      - econimal-network
networks:
  econimal-network:
    external: true
