spring:
  config:
    import:
    - classpath:secret.yml

  datasource:
    url: ${database.url}
    username: ${database.name}
    password: ${database.password}
    driver-class-name: ${database.driver-class-name}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      format_sql: true

server:
  servlet:
    context-path: /api

logging:
  level:
    root: info
    com.ssafy.econimal: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: debug
