name: Java CI with Gradle

# 워크플로우 실행 트리거 조건
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

# 실행할 작업 정의
jobs:
  build:
    runs-on: ubuntu-latest # 작업 실행할 환경
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository # 1. 체크아웃
        uses: actions/checkout@v4

      - name: Set up JDK 17 # 2. JDK 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # 배포판 선택

      - name: Setup Gradle # 3. Gradle 설정, 의존성 캐싱
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # 4) secret.yml 생성
      - name: Generate secret.yml
        working-directory: ./BackEnd/
        run: |
          cat << 'EOF' > secret.yml
          database:
            name:              ${{ secrets.DB_NAME }}
            password:          ${{ secrets.DB_PASSWORD }}
            url:               ${{ secrets.DATABASE_URL }}
            driver-class-name: com.mysql.cj.jdbc.Driver

          redis:
            host:     ${{ secrets.REDIS_HOST }}
            port:     ${{ secrets.REDIS_PORT }}
            password: ${{ secrets.REDIS_PASSWORD }}

          jwt:
            secret:             ${{ secrets.JWT_SECRET }}
            refresh-expiration: ${{ secrets.JWT_EXPIRATION }}
            pass-url:
              - "/api/users/signup"
              - "/api/users/login"
              - "/api/users/logout"
              - "/api/users/refresh"
              - "/api/users/password"
              - "/api/users/email-validation"
              - "/api/users/email/password/reset/request"
              - "/api/users/email/password/reset/confirm"
              - "/api/actuator"
              - "/api/actuator/health"
              - "/api/actuator/prometheus"
              - "/api/users/ex"

          cors:
            allowed-origins:
              - "http://localhost:5173"
              - "https://localhost:5173"
              - "http://j12a504.p.ssafy.io"
              - "https://j12a504.p.ssafy.io"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "PATCH"
              - "DELETE"
              - "OPTIONS"
            allowed-headers:
              - "Authorization"
              - "Content-Type"
              - "Cache-Control"
            exposed-headers:
              - "Authorization"
            allow-credentials: ${{ secrets.CORS_ALLOW_CREDENTIALS }}
            max-age:           ${{ secrets.CORS_MAX_AGE }}

          mail:
            host:       ${{ secrets.MAIL_HOST }}
            port:       ${{ secrets.MAIL_PORT }}
            username:   ${{ secrets.MAIL_USERNAME }}
            password:   ${{ secrets.MAIL_PASSWORD }}
            properties:
              mail:
                smtp:
                  auth:            ${{ secrets.MAIL_SMTP_AUTH }}
                  starttls:
                    enable:        ${{ secrets.MAIL_SMTP_STARTTLS_ENABLE }}

          ai:
            gpt:
              api-key: ${{ secrets.AI_API_KEY }}
              model:   ${{ secrets.AI_MODEL }}

          climate:
            api-url: ${{ secrets.CLIMATE_API_URL }}
          EOF

      - name: gradlew-setting # 권한 설정
        working-directory: ./BackEnd/
        run: |
          pwd
          ls -al
          gradle wrapper
          chmod +x ./gradle
          chmod +x ./gradlew.bat
          java --version
          ./gradlew clean build