name: Java CI with Gradle

# 워크플로우 실행 트리거 조건
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

# 실행할 작업 정의
jobs:
  build:
    runs-on: ubuntu-latest # 작업 실행할 환경
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository # 1. 체크아웃
        uses: actions/checkout@v4

      - name: Set up JDK 17 # 2. JDK 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # 배포판 선택

      - name: Setup Gradle # 3. Gradle 설정, 의존성 캐싱
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: gradlew-setting # 권한 설정
        working-directory: ./BackEnd/
        run: |
          pwd
          ls -al
          gradle wrapper
          chmod +x ./gradle
          chmod +x ./gradlew.bat
          java --version
          ./gradlew clean build